---
version: "3.9"
services:
  traceroute_exporter:
    image: "ghcr.io/akarneliuk/traceroute-exporter:latest"
    privileged: true
    ports:
      - "9101:9101"
    command:
      - "--targets=karneliuk.com,github.com,nokia.com"
      - "--workers=5"
      - "--interval=30"
...
