---
version: "3.9"
services:
  traceroute_exporter:
    image: "akarneliuk/traceroute-exporter:latest"
    privileged: true
    ports:
      - "9101:9101"
    command:
      - "--targets=karneliuk.com,github.com,nokia.com"
...