name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akarneliuk/traceroute-exporter:latest
    - name: Publish to registry
      run: |
        # Login to registry
        echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        # Push image
        docker push ghcr.io/akarneliuk/traceroute-exporter:latest
